on:
  push:
    branches:
      - master

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Compile constitution into HTML and PDF
        uses: xu-cheng/texlive-action@v3
        with:
          os: debian
          run: |
            # Install system dependencies
            export DEBIAN_FRONTEND=noninteractive
            apt-get update -y
            apt-get install -y latexml

            # Export to HTML
            latexml unigames_constitution.tex --dest=cons.xml
            latexmlpost cons.xml --dest=unigames_constitution.html

            # Export to PDF
            # PDFLatex needs multiple re-runs to get output correct.
            # Three should do.
            pdflatex unigames_constitution.tex
            pdflatex unigames_constitution.tex
            pdflatex unigames_constitution.tex
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: output 
          path: |
            unigames_constitution.html
            unigames_constitution.pdf
